In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# Imports
import numpy as np
import tensorflow as tf
# dp
from sklearn.model_selection import train_test_split
import os

tf.logging.set_verbosity(tf.logging.INFO)

# Our application logic will be added here
def cnn_model_fn(features, labels, mode):
    """Model function for CNN."""
    # Input Layer
    input_layer = tf.reshape(features["x"], [-1, 6, 300, 1]) # dp

    # Convolutional Layer #1 6*300*32
    conv1 = tf.layers.conv2d(
      inputs=input_layer,
      filters=32,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)

    # Pooling Layer #1 3*150*32
    pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)

    # Convolutional Layer #2 and Pooling Layer #2 3*150*64 
    conv2 = tf.layers.conv2d(
      inputs=pool1,
      filters=64,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)
    # 3x2 => 1*75*64
    pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[3, 2], strides=2)

    # Dense Layer
    pool2_flat = tf.reshape(pool2, [-1, 1 * 75 * 64])
    dense = tf.layers.dense(inputs=pool2_flat, units=1024, activation=tf.nn.relu)
    dropout = tf.layers.dropout(
      inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)

    # Logits Layer
    logits = tf.layers.dense(inputs=dropout, units=14) # 14 классов у Самодурова

    predictions = {
      # Generate predictions (for PREDICT and EVAL mode)
      "classes": tf.argmax(input=logits, axis=1),
      # Add `softmax_tensor` to the graph. It is used for PREDICT and by the
      # `logging_hook`.
      "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
    }

    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

    # Calculate Loss (for both TRAIN and EVAL modes)
    loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

    # Configure the Training Op (for TRAIN mode)
    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
        train_op = optimizer.minimize(loss=loss, global_step=tf.train.get_global_step())
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

    # Add evaluation metrics (for EVAL mode)
    eval_metric_ops = {"accuracy": tf.metrics.accuracy(labels=labels, predictions=predictions["classes"])}
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)

def main(unused_argv):
    # Load training and eval data
# dp
    cwd = r"C:\astrodata"
    os.chdir(cwd)
    compressedNpDataFile = r'14savedNpAstro0.npz'
    loaded = np.load(compressedNpDataFile)
    X_train, X_test, y_train, y_test = train_test_split(loaded['D'], loaded['L'], test_size=0.33, random_state=42)
    loaded.close()
# dp    
    #mnist = tf.contrib.learn.datasets.load_dataset("mnist")
    train_data = X_train   #mnist.train.images # Returns np.array
    train_labels = y_train #np.asarray(mnist.train.labels, dtype=np.int32)
    eval_data = X_test     #mnist.test.images # Returns np.array
    eval_labels = y_test   #np.asarray(mnist.test.labels, dtype=np.int32)
    
    # Create the Estimator
    astro_classifier = tf.estimator.Estimator(
    model_fn=cnn_model_fn, model_dir=r"C:\astrodata\CNN\model\astro_convnet_model")
    
    # Set up logging for predictions
    tensors_to_log = {"probabilities": "softmax_tensor"}
    logging_hook = tf.train.LoggingTensorHook(tensors=tensors_to_log, every_n_iter=50)
    
    # Train the model
    train_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x": train_data},
        y=train_labels,
        batch_size=100,
        num_epochs=None,
        shuffle=True)
    astro_classifier.train(
        input_fn=train_input_fn,
        steps=20000,
        hooks=[logging_hook])
    
    # Evaluate the model and print results
    eval_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x": eval_data},
        y=eval_labels,
        num_epochs=1,
        shuffle=False)
    eval_results = astro_classifier.evaluate(input_fn=eval_input_fn)
    print(eval_results)

if __name__ == "__main__":
    tf.app.run()

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\astrodata\\CNN\\model\\astro_convnet_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000287A16ACE48>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updatin

INFO:tensorflow:loss = 2.047394037246704, step = 6816 (27.732 sec)
INFO:tensorflow:probabilities = [[0.25720289 0.08332962 0.04995184 ... 0.04010288 0.04023262 0.03989601]
 [0.25720289 0.08332962 0.04995184 ... 0.04010288 0.04023262 0.03989601]
 [0.25720289 0.08332962 0.04995184 ... 0.04010288 0.04023262 0.03989601]
 ...
 [0.25720289 0.08332962 0.04995184 ... 0.04010288 0.04023262 0.03989601]
 [0.25720289 0.08332962 0.04995184 ... 0.04010288 0.04023262 0.03989601]
 [0.25720289 0.08332962 0.04995184 ... 0.04010288 0.04023262 0.03989601]] (13.836 sec)
INFO:tensorflow:global_step/sec: 3.61332
INFO:tensorflow:probabilities = [[0.25817123 0.08335229 0.04982041 ... 0.03993994 0.04007009 0.03973273]
 [0.25817123 0.08335229 0.04982041 ... 0.03993994 0.04007009 0.03973273]
 [0.25817123 0.08335229 0.04982041 ... 0.03993994 0.04007009 0.03973273]
 ...
 [0.25817123 0.08335229 0.04982041 ... 0.03993994 0.04007009 0.03973273]
 [0.25817123 0.08335229 0.04982041 ... 0.03993994 0.04007009 0.03973273]
 

INFO:tensorflow:probabilities = [[0.27219893 0.08376181 0.0480338  ... 0.03775978 0.03789597 0.0375465 ]
 [0.27219893 0.08376181 0.0480338  ... 0.03775978 0.03789597 0.0375465 ]
 [0.27219893 0.08376181 0.0480338  ... 0.03775978 0.03789597 0.0375465 ]
 ...
 [0.27219893 0.08376181 0.0480338  ... 0.03775978 0.03789597 0.0375465 ]
 [0.27219893 0.08376181 0.0480338  ... 0.03775978 0.03789597 0.0375465 ]
 [0.27219893 0.08376181 0.0480338  ... 0.03775978 0.03789597 0.0375465 ]] (13.718 sec)
INFO:tensorflow:loss = 1.883639931678772, step = 7616 (27.447 sec)
INFO:tensorflow:probabilities = [[0.27319927 0.08377156 0.04791556 ... 0.03761017 0.03774745 0.03739739]
 [0.27319927 0.08377156 0.04791556 ... 0.03761017 0.03774745 0.03739739]
 [0.27319927 0.08377156 0.04791556 ... 0.03761017 0.03774745 0.03739739]
 ...
 [0.27319927 0.08377156 0.04791556 ... 0.03761017 0.03774745 0.03739739]
 [0.27319927 0.08377156 0.04791556 ... 0.03761017 0.03774745 0.03739739]
 [0.27319927 0.08377156 0.04791556 ... 0.0

INFO:tensorflow:global_step/sec: 3.56895
INFO:tensorflow:probabilities = [[0.2862202  0.08419102 0.04619896 ... 0.03551254 0.03565025 0.03529369]
 [0.2862202  0.08419102 0.04619896 ... 0.03551254 0.03565025 0.03529369]
 [0.2862202  0.08419102 0.04619896 ... 0.03551254 0.03565025 0.03529369]
 ...
 [0.2862202  0.08419102 0.04619896 ... 0.03551254 0.03565025 0.03529369]
 [0.2862202  0.08419102 0.04619896 ... 0.03551254 0.03565025 0.03529369]
 [0.2862202  0.08419102 0.04619896 ... 0.03551254 0.03565025 0.03529369]] (13.954 sec)
INFO:tensorflow:loss = 1.928734540939331, step = 8416 (27.989 sec)
INFO:tensorflow:Saving checkpoints for 8464 into C:\astrodata\CNN\model\astro_convnet_model\model.ckpt.
INFO:tensorflow:probabilities = [[0.28707384 0.0842237  0.04608    ... 0.03537879 0.03551715 0.03515938]
 [0.28707384 0.0842237  0.04608    ... 0.03537879 0.03551715 0.03515938]
 [0.28707384 0.0842237  0.04608    ... 0.03537879 0.03551715 0.03515938]
 ...
 [0.28707384 0.0842237  0.04608    ... 0.03

INFO:tensorflow:loss = 1.8327144384384155, step = 9116 (27.928 sec)
INFO:tensorflow:probabilities = [[0.29734167 0.08477621 0.04464137 ... 0.03362474 0.03376642 0.03340133]
 [0.29734167 0.08477621 0.04464137 ... 0.03362474 0.03376642 0.03340133]
 [0.29734167 0.08477621 0.04464137 ... 0.03362474 0.03376642 0.03340133]
 ...
 [0.29734167 0.08477621 0.04464137 ... 0.03362474 0.03376642 0.03340133]
 [0.29734167 0.08477621 0.04464137 ... 0.03362474 0.03376642 0.03340133]
 [0.29734167 0.08477621 0.04464137 ... 0.03362474 0.03376642 0.03340133]] (13.975 sec)
INFO:tensorflow:global_step/sec: 3.57725
INFO:tensorflow:probabilities = [[0.29803629 0.08481275 0.04454641 ... 0.03350564 0.03364759 0.03328207]
 [0.29803629 0.08481275 0.04454641 ... 0.03350564 0.03364759 0.03328207]
 [0.29803629 0.08481275 0.04454641 ... 0.03350564 0.03364759 0.03328207]
 ...
 [0.29803629 0.08481275 0.04454641 ... 0.03350564 0.03364759 0.03328207]
 [0.29803629 0.08481275 0.04454641 ... 0.03350564 0.03364759 0.03328207]


INFO:tensorflow:probabilities = [[0.3073606  0.08540326 0.04325425 ... 0.03191999 0.03206609 0.03169297]
 [0.3073606  0.08540326 0.04325425 ... 0.03191999 0.03206609 0.03169297]
 [0.3073606  0.08540326 0.04325425 ... 0.03191999 0.03206609 0.03169297]
 ...
 [0.3073606  0.08540326 0.04325425 ... 0.03191999 0.03206609 0.03169297]
 [0.3073606  0.08540326 0.04325425 ... 0.03191999 0.03206609 0.03169297]
 [0.3073606  0.08540326 0.04325425 ... 0.03191999 0.03206609 0.03169297]] (13.775 sec)
INFO:tensorflow:loss = 1.954781413078308, step = 9916 (27.567 sec)
INFO:tensorflow:probabilities = [[0.30807307 0.08545731 0.04317402 ... 0.0318123  0.03195832 0.03158609]
 [0.30807307 0.08545731 0.04317402 ... 0.0318123  0.03195832 0.03158609]
 [0.30807307 0.08545731 0.04317402 ... 0.0318123  0.03195832 0.03158609]
 ...
 [0.30807307 0.08545731 0.04317402 ... 0.0318123  0.03195832 0.03158609]
 [0.30807307 0.08545731 0.04317402 ... 0.0318123  0.03195832 0.03158609]
 [0.30807307 0.08545731 0.04317402 ... 0.0

INFO:tensorflow:probabilities = [[0.31558611 0.0860986  0.04201508 ... 0.03038987 0.03053661 0.0301596 ]
 [0.31558611 0.0860986  0.04201508 ... 0.03038987 0.03053661 0.0301596 ]
 [0.31558611 0.0860986  0.04201508 ... 0.03038987 0.03053661 0.0301596 ]
 ...
 [0.31558611 0.0860986  0.04201508 ... 0.03038987 0.03053661 0.0301596 ]
 [0.31558611 0.0860986  0.04201508 ... 0.03038987 0.03053661 0.0301596 ]
 [0.31558611 0.0860986  0.04201508 ... 0.03038987 0.03053661 0.0301596 ]] (14.984 sec)
INFO:tensorflow:global_step/sec: 3.48345
INFO:tensorflow:probabilities = [[0.31615755 0.08614068 0.04193262 ... 0.03029087 0.03043874 0.0300608 ]
 [0.31615755 0.08614068 0.04193262 ... 0.03029087 0.03043874 0.0300608 ]
 [0.31615755 0.08614068 0.04193262 ... 0.03029087 0.03043874 0.0300608 ]
 ...
 [0.31615755 0.08614068 0.04193262 ... 0.03029087 0.03043874 0.0300608 ]
 [0.31615755 0.08614068 0.04193262 ... 0.03029087 0.03043874 0.0300608 ]
 [0.31615755 0.08614068 0.04193262 ... 0.03029087 0.03043874 0.03006

INFO:tensorflow:loss = 1.7950637340545654, step = 11416 (27.480 sec)
INFO:tensorflow:probabilities = [[0.32312954 0.08698762 0.04083301 ... 0.02891618 0.02906601 0.02868232]
 [0.32312954 0.08698762 0.04083301 ... 0.02891618 0.02906601 0.02868232]
 [0.32312954 0.08698762 0.04083301 ... 0.02891618 0.02906601 0.02868232]
 ...
 [0.32312954 0.08698762 0.04083301 ... 0.02891618 0.02906601 0.02868232]
 [0.32312954 0.08698762 0.04083301 ... 0.02891618 0.02906601 0.02868232]
 [0.32312954 0.08698762 0.04083301 ... 0.02891618 0.02906601 0.02868232]] (13.879 sec)
INFO:tensorflow:global_step/sec: 3.6062
INFO:tensorflow:probabilities = [[0.32365363 0.08705617 0.04075995 ... 0.02882683 0.02897772 0.02859317]
 [0.32365363 0.08705617 0.04075995 ... 0.02882683 0.02897772 0.02859317]
 [0.32365363 0.08705617 0.04075995 ... 0.02882683 0.02897772 0.02859317]
 ...
 [0.32365363 0.08705617 0.04075995 ... 0.02882683 0.02897772 0.02859317]
 [0.32365363 0.08705617 0.04075995 ... 0.02882683 0.02897772 0.02859317]


INFO:tensorflow:probabilities = [[0.3295265  0.08785021 0.03985544 ... 0.0276639  0.02781577 0.02742771]
 [0.3295265  0.08785021 0.03985544 ... 0.0276639  0.02781577 0.02742771]
 [0.3295265  0.08785021 0.03985544 ... 0.0276639  0.02781577 0.02742771]
 ...
 [0.3295265  0.08785021 0.03985544 ... 0.0276639  0.02781577 0.02742771]
 [0.3295265  0.08785021 0.03985544 ... 0.0276639  0.02781577 0.02742771]
 [0.3295265  0.08785021 0.03985544 ... 0.0276639  0.02781577 0.02742771]] (14.047 sec)
INFO:tensorflow:loss = 1.7183737754821777, step = 12216 (27.954 sec)
INFO:tensorflow:probabilities = [[0.32985619 0.08789245 0.03978987 ... 0.02758499 0.02773677 0.02734816]
 [0.32985619 0.08789245 0.03978987 ... 0.02758499 0.02773677 0.02734816]
 [0.32985619 0.08789245 0.03978987 ... 0.02758499 0.02773677 0.02734816]
 ...
 [0.32985619 0.08789245 0.03978987 ... 0.02758499 0.02773677 0.02734816]
 [0.32985619 0.08789245 0.03978987 ... 0.02758499 0.02773677 0.02734816]
 [0.32985619 0.08789245 0.03978987 ... 0

INFO:tensorflow:loss = 1.8006430864334106, step = 12916 (27.446 sec)
INFO:tensorflow:probabilities = [[0.3345709  0.08876561 0.03896123 ... 0.02652685 0.02668064 0.02628824]
 [0.3345709  0.08876561 0.03896123 ... 0.02652685 0.02668064 0.02628824]
 [0.3345709  0.08876561 0.03896123 ... 0.02652685 0.02668064 0.02628824]
 ...
 [0.3345709  0.08876561 0.03896123 ... 0.02652685 0.02668064 0.02628824]
 [0.3345709  0.08876561 0.03896123 ... 0.02652685 0.02668064 0.02628824]
 [0.3345709  0.08876561 0.03896123 ... 0.02652685 0.02668064 0.02628824]] (13.700 sec)
INFO:tensorflow:global_step/sec: 3.65303
INFO:tensorflow:probabilities = [[0.33472417 0.08889789 0.03890962 ... 0.0264592  0.02661239 0.02621993]
 [0.33472417 0.08889789 0.03890962 ... 0.0264592  0.02661239 0.02621993]
 [0.33472417 0.08889789 0.03890962 ... 0.0264592  0.02661239 0.02621993]
 ...
 [0.33472417 0.08889789 0.03890962 ... 0.0264592  0.02661239 0.02621993]
 [0.33472417 0.08889789 0.03890962 ... 0.0264592  0.02661239 0.02621993]

INFO:tensorflow:probabilities = [[0.33903444 0.08981444 0.03816401 ... 0.02549135 0.02564718 0.02525018]
 [0.33903444 0.08981444 0.03816401 ... 0.02549135 0.02564718 0.02525018]
 [0.33903444 0.08981444 0.03816401 ... 0.02549135 0.02564718 0.02525018]
 ...
 [0.33903444 0.08981444 0.03816401 ... 0.02549135 0.02564718 0.02525018]
 [0.33903444 0.08981444 0.03816401 ... 0.02549135 0.02564718 0.02525018]
 [0.33903444 0.08981444 0.03816401 ... 0.02549135 0.02564718 0.02525018]] (13.677 sec)
INFO:tensorflow:loss = 1.9388870000839233, step = 13716 (27.425 sec)
INFO:tensorflow:probabilities = [[0.33940523 0.08987908 0.03811197 ... 0.02542514 0.02558191 0.02518339]
 [0.33940523 0.08987908 0.03811197 ... 0.02542514 0.02558191 0.02518339]
 [0.33940523 0.08987908 0.03811197 ... 0.02542514 0.02558191 0.02518339]
 ...
 [0.33940523 0.08987908 0.03811197 ... 0.02542514 0.02558191 0.02518339]
 [0.33940523 0.08987908 0.03811197 ... 0.02542514 0.02558191 0.02518339]
 [0.33940523 0.08987908 0.03811197 ... 0

INFO:tensorflow:global_step/sec: 3.64992
INFO:tensorflow:probabilities = [[0.34334333 0.0909198  0.037412   ... 0.02448181 0.02463775 0.0242372 ]
 [0.34334333 0.0909198  0.037412   ... 0.02448181 0.02463775 0.0242372 ]
 [0.34334333 0.0909198  0.037412   ... 0.02448181 0.02463775 0.0242372 ]
 ...
 [0.34334333 0.0909198  0.037412   ... 0.02448181 0.02463775 0.0242372 ]
 [0.34334333 0.0909198  0.037412   ... 0.02448181 0.02463775 0.0242372 ]
 [0.34334333 0.0909198  0.037412   ... 0.02448181 0.02463775 0.0242372 ]] (13.693 sec)
INFO:tensorflow:loss = 1.790697455406189, step = 14516 (27.397 sec)
INFO:tensorflow:probabilities = [[0.34345236 0.09098241 0.03736625 ... 0.02442198 0.02457858 0.02417802]
 [0.34345236 0.09098241 0.03736625 ... 0.02442198 0.02457858 0.02417802]
 [0.34345236 0.09098241 0.03736625 ... 0.02442198 0.02457858 0.02417802]
 ...
 [0.34345236 0.09098241 0.03736625 ... 0.02442198 0.02457858 0.02417802]
 [0.34345236 0.09098241 0.03736625 ... 0.02442198 0.02457858 0.02417802]


INFO:tensorflow:loss = 1.7585256099700928, step = 15216 (27.363 sec)
INFO:tensorflow:probabilities = [[0.34646339 0.09203096 0.03677707 ... 0.02361581 0.02377388 0.02336942]
 [0.34646339 0.09203096 0.03677707 ... 0.02361581 0.02377388 0.02336942]
 [0.34646339 0.09203096 0.03677707 ... 0.02361581 0.02377388 0.02336942]
 ...
 [0.34646339 0.09203096 0.03677707 ... 0.02361581 0.02377388 0.02336942]
 [0.34646339 0.09203096 0.03677707 ... 0.02361581 0.02377388 0.02336942]
 [0.34646339 0.09203096 0.03677707 ... 0.02361581 0.02377388 0.02336942]] (13.678 sec)
INFO:tensorflow:global_step/sec: 3.65161
INFO:tensorflow:probabilities = [[0.34669891 0.09208751 0.03672744 ... 0.02355797 0.02371713 0.02331154]
 [0.34669891 0.09208751 0.03672744 ... 0.02355797 0.02371713 0.02331154]
 [0.34669891 0.09208751 0.03672744 ... 0.02355797 0.02371713 0.02331154]
 ...
 [0.34669891 0.09208751 0.03672744 ... 0.02355797 0.02371713 0.02331154]
 [0.34669891 0.09208751 0.03672744 ... 0.02355797 0.02371713 0.02331154]

INFO:tensorflow:probabilities = [[0.34953332 0.09315404 0.03620258 ... 0.0228152  0.02297642 0.02256758]
 [0.34953332 0.09315404 0.03620258 ... 0.0228152  0.02297642 0.02256758]
 [0.34953332 0.09315404 0.03620258 ... 0.0228152  0.02297642 0.02256758]
 ...
 [0.34953332 0.09315404 0.03620258 ... 0.0228152  0.02297642 0.02256758]
 [0.34953332 0.09315404 0.03620258 ... 0.0228152  0.02297642 0.02256758]
 [0.34953332 0.09315404 0.03620258 ... 0.0228152  0.02297642 0.02256758]] (13.689 sec)
INFO:tensorflow:loss = 1.716306447982788, step = 16016 (27.371 sec)
INFO:tensorflow:probabilities = [[0.34995923 0.09323642 0.03616294 ... 0.02276288 0.02292355 0.02251454]
 [0.34995923 0.09323642 0.03616294 ... 0.02276288 0.02292355 0.02251454]
 [0.34995923 0.09323642 0.03616294 ... 0.02276288 0.02292355 0.02251454]
 ...
 [0.34995923 0.09323642 0.03616294 ... 0.02276288 0.02292355 0.02251454]
 [0.34995923 0.09323642 0.03616294 ... 0.02276288 0.02292355 0.02251454]
 [0.34995923 0.09323642 0.03616294 ... 0.

INFO:tensorflow:global_step/sec: 3.65006
INFO:tensorflow:probabilities = [[0.35227103 0.09433339 0.03564987 ... 0.02202896 0.02219042 0.02177875]
 [0.35227103 0.09433339 0.03564987 ... 0.02202896 0.02219042 0.02177875]
 [0.35227103 0.09433339 0.03564987 ... 0.02202896 0.02219042 0.02177875]
 ...
 [0.35227103 0.09433339 0.03564987 ... 0.02202896 0.02219042 0.02177875]
 [0.35227103 0.09433339 0.03564987 ... 0.02202896 0.02219042 0.02177875]
 [0.35227103 0.09433339 0.03564987 ... 0.02202896 0.02219042 0.02177875]] (13.729 sec)
INFO:tensorflow:loss = 1.6740877628326416, step = 16816 (27.425 sec)
INFO:tensorflow:probabilities = [[0.35223349 0.09443904 0.03562621 ... 0.02198358 0.02214541 0.02173351]
 [0.35223349 0.09443904 0.03562621 ... 0.02198358 0.02214541 0.02173351]
 [0.35223349 0.09443904 0.03562621 ... 0.02198358 0.02214541 0.02173351]
 ...
 [0.35223349 0.09443904 0.03562621 ... 0.02198358 0.02214541 0.02173351]
 [0.35223349 0.09443904 0.03562621 ... 0.02198358 0.02214541 0.02173351]

INFO:tensorflow:loss = 1.7027819156646729, step = 17516 (27.824 sec)
INFO:tensorflow:probabilities = [[0.35422625 0.09553687 0.03518912 ... 0.02134893 0.02151203 0.0210967 ]
 [0.35422625 0.09553687 0.03518912 ... 0.02134893 0.02151203 0.0210967 ]
 [0.35422625 0.09553687 0.03518912 ... 0.02134893 0.02151203 0.0210967 ]
 ...
 [0.35422625 0.09553687 0.03518912 ... 0.02134893 0.02151203 0.0210967 ]
 [0.35422625 0.09553687 0.03518912 ... 0.02134893 0.02151203 0.0210967 ]
 [0.35422625 0.09553687 0.03518912 ... 0.02134893 0.02151203 0.0210967 ]] (13.893 sec)
INFO:tensorflow:global_step/sec: 3.59784
INFO:tensorflow:probabilities = [[0.35440014 0.09563613 0.03516409 ... 0.02130714 0.02146976 0.02105442]
 [0.35440014 0.09563613 0.03516409 ... 0.02130714 0.02146976 0.02105442]
 [0.35440014 0.09563613 0.03516409 ... 0.02130714 0.02146976 0.02105442]
 ...
 [0.35440014 0.09563613 0.03516409 ... 0.02130714 0.02146976 0.02105442]
 [0.35440014 0.09563613 0.03516409 ... 0.02130714 0.02146976 0.02105442]

INFO:tensorflow:probabilities = [[0.35665578 0.09670379 0.03477425 ... 0.02071291 0.02087736 0.02045899]
 [0.35665578 0.09670379 0.03477425 ... 0.02071291 0.02087736 0.02045899]
 [0.35665578 0.09670379 0.03477425 ... 0.02071291 0.02087736 0.02045899]
 ...
 [0.35665578 0.09670379 0.03477425 ... 0.02071291 0.02087736 0.02045899]
 [0.35665578 0.09670379 0.03477425 ... 0.02071291 0.02087736 0.02045899]
 [0.35665578 0.09670379 0.03477425 ... 0.02071291 0.02087736 0.02045899]] (13.938 sec)
INFO:tensorflow:loss = 1.7558192014694214, step = 18316 (27.758 sec)
INFO:tensorflow:probabilities = [[0.35666024 0.09679352 0.03476472 ... 0.02067442 0.02083943 0.02042061]
 [0.35666024 0.09679352 0.03476472 ... 0.02067442 0.02083943 0.02042061]
 [0.35666024 0.09679352 0.03476472 ... 0.02067442 0.02083943 0.02042061]
 ...
 [0.35666024 0.09679352 0.03476472 ... 0.02067442 0.02083943 0.02042061]
 [0.35666024 0.09679352 0.03476472 ... 0.02067442 0.02083943 0.02042061]
 [0.35666024 0.09679352 0.03476472 ... 0

INFO:tensorflow:global_step/sec: 3.65657
INFO:tensorflow:probabilities = [[0.35814237 0.09794942 0.03437796 ... 0.02008632 0.02025163 0.01983024]
 [0.35814237 0.09794942 0.03437796 ... 0.02008632 0.02025163 0.01983024]
 [0.35814237 0.09794942 0.03437796 ... 0.02008632 0.02025163 0.01983024]
 ...
 [0.35814237 0.09794942 0.03437796 ... 0.02008632 0.02025163 0.01983024]
 [0.35814237 0.09794942 0.03437796 ... 0.02008632 0.02025163 0.01983024]
 [0.35814237 0.09794942 0.03437796 ... 0.02008632 0.02025163 0.01983024]] (13.677 sec)
INFO:tensorflow:loss = 1.6716631650924683, step = 19116 (27.345 sec)
INFO:tensorflow:probabilities = [[0.35817463 0.0980371  0.03435584 ... 0.02004922 0.02021446 0.01979288]
 [0.35817463 0.0980371  0.03435584 ... 0.02004922 0.02021446 0.01979288]
 [0.35817463 0.0980371  0.03435584 ... 0.02004922 0.02021446 0.01979288]
 ...
 [0.35817463 0.0980371  0.03435584 ... 0.02004922 0.02021446 0.01979288]
 [0.35817463 0.0980371  0.03435584 ... 0.02004922 0.02021446 0.01979288]

INFO:tensorflow:loss = 1.8959248065948486, step = 19816 (27.371 sec)
INFO:tensorflow:probabilities = [[0.35979332 0.09912989 0.03403278 ... 0.01953537 0.01970255 0.0192775 ]
 [0.35979332 0.09912989 0.03403278 ... 0.01953537 0.01970255 0.0192775 ]
 [0.35979332 0.09912989 0.03403278 ... 0.01953537 0.01970255 0.0192775 ]
 ...
 [0.35979332 0.09912989 0.03403278 ... 0.01953537 0.01970255 0.0192775 ]
 [0.35979332 0.09912989 0.03403278 ... 0.01953537 0.01970255 0.0192775 ]
 [0.35979332 0.09912989 0.03403278 ... 0.01953537 0.01970255 0.0192775 ]] (13.679 sec)
INFO:tensorflow:global_step/sec: 3.64886
INFO:tensorflow:probabilities = [[0.35997573 0.09918969 0.03401881 ... 0.01949956 0.01966765 0.01924221]
 [0.35997573 0.09918969 0.03401881 ... 0.01949956 0.01966765 0.01924221]
 [0.35997573 0.09918969 0.03401881 ... 0.01949956 0.01966765 0.01924221]
 ...
 [0.35997573 0.09918969 0.03401881 ... 0.01949956 0.01966765 0.01924221]
 [0.35997573 0.09918969 0.03401881 ... 0.01949956 0.01966765 0.01924221]

INFO:tensorflow:probabilities = [[0.36129678 0.10023526 0.0337401  ... 0.0190192  0.01918684 0.01875977]
 [0.36129678 0.10023526 0.0337401  ... 0.0190192  0.01918684 0.01875977]
 [0.36129678 0.10023526 0.0337401  ... 0.0190192  0.01918684 0.01875977]
 ...
 [0.36129678 0.10023526 0.0337401  ... 0.0190192  0.01918684 0.01875977]
 [0.36129678 0.10023526 0.0337401  ... 0.0190192  0.01918684 0.01875977]
 [0.36129678 0.10023526 0.0337401  ... 0.0190192  0.01918684 0.01875977]] (13.652 sec)
INFO:tensorflow:loss = 1.8206981420516968, step = 20616 (27.332 sec)
INFO:tensorflow:probabilities = [[0.3612147  0.10028753 0.03371812 ... 0.01898736 0.01915514 0.01872749]
 [0.3612147  0.10028753 0.03371812 ... 0.01898736 0.01915514 0.01872749]
 [0.3612147  0.10028753 0.03371812 ... 0.01898736 0.01915514 0.01872749]
 ...
 [0.3612147  0.10028753 0.03371812 ... 0.01898736 0.01915514 0.01872749]
 [0.3612147  0.10028753 0.03371812 ... 0.01898736 0.01915514 0.01872749]
 [0.3612147  0.10028753 0.03371812 ... 0

INFO:tensorflow:global_step/sec: 3.64846
INFO:tensorflow:probabilities = [[0.36226379 0.10147205 0.03344204 ... 0.01850586 0.01867505 0.01824464]
 [0.36226379 0.10147205 0.03344204 ... 0.01850586 0.01867505 0.01824464]
 [0.36226379 0.10147205 0.03344204 ... 0.01850586 0.01867505 0.01824464]
 ...
 [0.36226379 0.10147205 0.03344204 ... 0.01850586 0.01867505 0.01824464]
 [0.36226379 0.10147205 0.03344204 ... 0.01850586 0.01867505 0.01824464]
 [0.36226379 0.10147205 0.03344204 ... 0.01850586 0.01867505 0.01824464]] (13.695 sec)
INFO:tensorflow:loss = 1.6261945962905884, step = 21416 (27.382 sec)
INFO:tensorflow:probabilities = [[0.36240478 0.10153922 0.03342381 ... 0.01847372 0.0186432  0.01821247]
 [0.36240478 0.10153922 0.03342381 ... 0.01847372 0.0186432  0.01821247]
 [0.36240478 0.10153922 0.03342381 ... 0.01847372 0.0186432  0.01821247]
 ...
 [0.36240478 0.10153922 0.03342381 ... 0.01847372 0.0186432  0.01821247]
 [0.36240478 0.10153922 0.03342381 ... 0.01847372 0.0186432  0.01821247]

INFO:tensorflow:loss = 1.9756929874420166, step = 22116 (27.548 sec)
INFO:tensorflow:probabilities = [[0.36368024 0.10259246 0.03319644 ... 0.0180504  0.0182213  0.01778772]
 [0.36368024 0.10259246 0.03319644 ... 0.0180504  0.0182213  0.01778772]
 [0.36368024 0.10259246 0.03319644 ... 0.0180504  0.0182213  0.01778772]
 ...
 [0.36368024 0.10259246 0.03319644 ... 0.0180504  0.0182213  0.01778772]
 [0.36368024 0.10259246 0.03319644 ... 0.0180504  0.0182213  0.01778772]
 [0.36368024 0.10259246 0.03319644 ... 0.0180504  0.0182213  0.01778772]] (13.679 sec)
INFO:tensorflow:global_step/sec: 3.648
INFO:tensorflow:probabilities = [[0.36389506 0.102646   0.0331856  ... 0.0180203  0.01819112 0.01775775]
 [0.36389506 0.102646   0.0331856  ... 0.0180203  0.01819112 0.01775775]
 [0.36389506 0.102646   0.0331856  ... 0.0180203  0.01819112 0.01775775]
 ...
 [0.36389506 0.102646   0.0331856  ... 0.0180203  0.01819112 0.01775775]
 [0.36389506 0.102646   0.0331856  ... 0.0180203  0.01819112 0.01775775]
 

INFO:tensorflow:probabilities = [[0.36451858 0.10364698 0.03297331 ... 0.0176224  0.01779355 0.0173581 ]
 [0.36451858 0.10364698 0.03297331 ... 0.0176224  0.01779355 0.0173581 ]
 [0.36451858 0.10364698 0.03297331 ... 0.0176224  0.01779355 0.0173581 ]
 ...
 [0.36451858 0.10364698 0.03297331 ... 0.0176224  0.01779355 0.0173581 ]
 [0.36451858 0.10364698 0.03297331 ... 0.0176224  0.01779355 0.0173581 ]
 [0.36451858 0.10364698 0.03297331 ... 0.0176224  0.01779355 0.0173581 ]] (13.777 sec)
INFO:tensorflow:loss = 1.7111610174179077, step = 22916 (27.578 sec)
INFO:tensorflow:probabilities = [[0.36458818 0.10370796 0.03296022 ... 0.0175946  0.01776621 0.01733024]
 [0.36458818 0.10370796 0.03296022 ... 0.0175946  0.01776621 0.01733024]
 [0.36458818 0.10370796 0.03296022 ... 0.0175946  0.01776621 0.01733024]
 ...
 [0.36458818 0.10370796 0.03296022 ... 0.0175946  0.01776621 0.01733024]
 [0.36458818 0.10370796 0.03296022 ... 0.0175946  0.01776621 0.01733024]
 [0.36458818 0.10370796 0.03296022 ... 0

INFO:tensorflow:Saving checkpoints for 23703 into C:\astrodata\CNN\model\astro_convnet_model\model.ckpt.
INFO:tensorflow:global_step/sec: 3.49953
INFO:tensorflow:probabilities = [[0.36538519 0.10481969 0.03275568 ... 0.01719135 0.01736408 0.01692508]
 [0.36538519 0.10481969 0.03275568 ... 0.01719135 0.01736408 0.01692508]
 [0.36538519 0.10481969 0.03275568 ... 0.01719135 0.01736408 0.01692508]
 ...
 [0.36538519 0.10481969 0.03275568 ... 0.01719135 0.01736408 0.01692508]
 [0.36538519 0.10481969 0.03275568 ... 0.01719135 0.01736408 0.01692508]
 [0.36538519 0.10481969 0.03275568 ... 0.01719135 0.01736408 0.01692508]] (14.897 sec)
INFO:tensorflow:loss = 1.7438424825668335, step = 23716 (28.578 sec)
INFO:tensorflow:probabilities = [[0.36553618 0.1048933  0.0327412  ... 0.01716432 0.01733784 0.01689835]
 [0.36553618 0.1048933  0.0327412  ... 0.01716432 0.01733784 0.01689835]
 [0.36553618 0.1048933  0.0327412  ... 0.01716432 0.01733784 0.01689835]
 ...
 [0.36553618 0.1048933  0.0327412  ... 0

INFO:tensorflow:loss = 1.5122997760772705, step = 24416 (27.388 sec)
INFO:tensorflow:probabilities = [[0.36653167 0.10582517 0.03258421 ... 0.01680756 0.0169817  0.01654029]
 [0.36653167 0.10582517 0.03258421 ... 0.01680756 0.0169817  0.01654029]
 [0.36653167 0.10582517 0.03258421 ... 0.01680756 0.0169817  0.01654029]
 ...
 [0.36653167 0.10582517 0.03258421 ... 0.01680756 0.0169817  0.01654029]
 [0.36653167 0.10582517 0.03258421 ... 0.01680756 0.0169817  0.01654029]
 [0.36653167 0.10582517 0.03258421 ... 0.01680756 0.0169817  0.01654029]] (13.696 sec)
INFO:tensorflow:global_step/sec: 3.64959
INFO:tensorflow:probabilities = [[0.36645578 0.10589544 0.03257471 ... 0.01678351 0.01695742 0.01651618]
 [0.36645578 0.10589544 0.03257471 ... 0.01678351 0.01695742 0.01651618]
 [0.36645578 0.10589544 0.03257471 ... 0.01678351 0.01695742 0.01651618]
 ...
 [0.36645578 0.10589544 0.03257471 ... 0.01678351 0.01695742 0.01651618]
 [0.36645578 0.10589544 0.03257471 ... 0.01678351 0.01695742 0.01651618]

INFO:tensorflow:probabilities = [[0.36708239 0.10682403 0.03241068 ... 0.01644367 0.01661868 0.01617525]
 [0.36708239 0.10682403 0.03241068 ... 0.01644367 0.01661868 0.01617525]
 [0.36708239 0.10682403 0.03241068 ... 0.01644367 0.01661868 0.01617525]
 ...
 [0.36708239 0.10682403 0.03241068 ... 0.01644367 0.01661868 0.01617525]
 [0.36708239 0.10682403 0.03241068 ... 0.01644367 0.01661868 0.01617525]
 [0.36708239 0.10682403 0.03241068 ... 0.01644367 0.01661868 0.01617525]] (13.681 sec)
INFO:tensorflow:loss = 1.6645079851150513, step = 25216 (27.365 sec)
INFO:tensorflow:probabilities = [[0.3668853  0.1069617  0.03240395 ... 0.0164238  0.01659779 0.01615447]
 [0.3668853  0.1069617  0.03240395 ... 0.0164238  0.01659779 0.01615447]
 [0.3668853  0.1069617  0.03240395 ... 0.0164238  0.01659779 0.01615447]
 ...
 [0.3668853  0.1069617  0.03240395 ... 0.0164238  0.01659779 0.01615447]
 [0.3668853  0.1069617  0.03240395 ... 0.0164238  0.01659779 0.01615447]
 [0.3668853  0.1069617  0.03240395 ... 0

INFO:tensorflow:loss = 1.7826008796691895, step = 25916 (28.677 sec)
INFO:tensorflow:probabilities = [[0.36765114 0.10785703 0.03226689 ... 0.01610202 0.01627776 0.01583145]
 [0.36765114 0.10785703 0.03226689 ... 0.01610202 0.01627776 0.01583145]
 [0.36765114 0.10785703 0.03226689 ... 0.01610202 0.01627776 0.01583145]
 ...
 [0.36765114 0.10785703 0.03226689 ... 0.01610202 0.01627776 0.01583145]
 [0.36765114 0.10785703 0.03226689 ... 0.01610202 0.01627776 0.01583145]
 [0.36765114 0.10785703 0.03226689 ... 0.01610202 0.01627776 0.01583145]] (13.689 sec)
INFO:tensorflow:global_step/sec: 3.65617
INFO:tensorflow:probabilities = [[0.36785282 0.10791552 0.03225634 ... 0.01607807 0.01625455 0.01580764]
 [0.36785282 0.10791552 0.03225634 ... 0.01607807 0.01625455 0.01580764]
 [0.36785282 0.10791552 0.03225634 ... 0.01607807 0.01625455 0.01580764]
 ...
 [0.36785282 0.10791552 0.03225634 ... 0.01607807 0.01625455 0.01580764]
 [0.36785282 0.10791552 0.03225634 ... 0.01607807 0.01625455 0.01580764]

SystemExit: 

C:\Users\dvperv\Anaconda3\envs\tf36gpu\lib\site-packages\IPython\core\interactiveshell.py:3275: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
